apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  NODE_ENV: ZGV2ZWxvcG1lbnQ=
  MONGODB_URL: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvZGF0YWJhc2U=